services:
  api-produto:
    container_name: api-produto
    build:
      context: .docker/node/
      dockerfile: Dockerfile
    entrypoint: .docker/node/entrypoint.sh
    ports:
      - "3003:3003"
      - "7003:7003"
    volumes:
      - .:/home/node/app

  db-produto:
    container_name: db-produto
    build:
      context: .docker/postgres/
      dockerfile: Dockerfile
    command: postgres -c log_statement=all -p 5003
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: api-produto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5003:5003"
